/* A recursive-descent parser generated by greg 0.4.3 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct _GREG;
#define YYRULECOUNT 18

/* PEG Markdown Highlight
 * Copyright 2011 Ali Rantakari -- http://hasseg.org
 * Licensed under the GPL2+ and MIT licenses (see LICENSE for more info).
 * 
 * styleparser.leg
 * 
 */

#include "styleparser.h"
#include <stdbool.h>
#include <stdarg.h>
#include <ctype.h>


// vasprintf is not in the C standard nor in POSIX so we provide our own
int our_vasprintf(char **strptr, const char *fmt, va_list argptr)
{
    int ret;
    va_list argptr2;
    *strptr = NULL;
    
    va_copy(argptr2, argptr);
    ret = vsnprintf(NULL, 0, fmt, argptr2);
    if (ret <= 0)
        return ret;
    
    *strptr = (char *)malloc(ret+1);
    if (*strptr == NULL)
        return -1;
    
    va_copy(argptr2, argptr);
    ret = vsnprintf(*strptr, ret+1, fmt, argptr2);
    
    return ret;
}



// Set custom symbol name prefix to avoid name collisions with the main
// PEG Markdown Highlight parser:
#define YY_NAME(N) style_yy##N


attr_argb_color *new_argb_color(int r, int g, int b, int a) {
    attr_argb_color *c = (attr_argb_color *)malloc(sizeof(attr_argb_color));
    c->red = r; c->green = g; c->blue = b; c->alpha = a;
    return c;
}
attr_argb_color *new_argb_from_hex(long hex, bool has_alpha) {
    // 0xaarrggbb
    int a = has_alpha ? ((hex >> 24) & 0xFF) : 255;
    int r = ((hex >> 16) & 0xFF);
    int g = ((hex >> 8) & 0xFF);
    int b = (hex & 0xFF);
    return new_argb_color(r,g,b,a);
}
attr_argb_color *new_argb_from_hex_str(char *str) {
    // "aarrggbb"
    long num = strtol(str, NULL, 16);
    return new_argb_from_hex(num, (strlen(str) == 8));
}

attr_value *new_attr_value() {
    return (attr_value *)malloc(sizeof(attr_value));
}

style_attribute *new_attr(char *name, attr_type type) {
    style_attribute *attr = (style_attribute *)malloc(sizeof(style_attribute));
    attr->name = strdup(name);
    attr->type = type;
    attr->next = NULL;
    return attr;
}


// Parsing context data
typedef struct
{
    char *input;
    int pos;
    void (*error_callback)(char *);
    int styles_pos;
    style_collection *styles;
} style_parser_data;





typedef struct sem_value
{
    char *name;
    char *value;
    struct sem_value *next;
} sem_value;

sem_value *new_sem_value(char *name, char *value)
{
    sem_value *v = (sem_value *)malloc(sizeof(sem_value));
    v->name = name;
    v->value = value;
    v->next = NULL;
    return v;
}

static sem_value *cons(sem_value *elem, sem_value *list)
{
    elem->next = list;
    return elem;
}


char **get_element_type_names()
{
    static char **elem_type_names = NULL;
    if (elem_type_names == NULL)
    {
        elem_type_names = (char **)malloc(sizeof(char*) * NUM_LANG_TYPES);
        elem_type_names[LINK] = "LINK";
        elem_type_names[AUTO_LINK_URL] = "AUTO_LINK_URL";
        elem_type_names[AUTO_LINK_EMAIL] = "AUTO_LINK_EMAIL";
        elem_type_names[IMAGE] = "IMAGE";
        elem_type_names[CODE] = "CODE";
        elem_type_names[HTML] = "HTML";
        elem_type_names[HTML_ENTITY] = "HTML_ENTITY";
        elem_type_names[EMPH] = "EMPH";
        elem_type_names[STRONG] = "STRONG";
        elem_type_names[LIST_BULLET] = "LIST_BULLET";
        elem_type_names[LIST_ENUMERATOR] = "LIST_ENUMERATOR";
        elem_type_names[COMMENT] = "COMMENT";
        elem_type_names[H1] = "H1";
        elem_type_names[H2] = "H2";
        elem_type_names[H3] = "H3";
        elem_type_names[H4] = "H4";
        elem_type_names[H5] = "H5";
        elem_type_names[H6] = "H6";
        elem_type_names[BLOCKQUOTE] = "BLOCKQUOTE";
        elem_type_names[VERBATIM] = "VERBATIM";
        elem_type_names[HTMLBLOCK] = "HTMLBLOCK";
        elem_type_names[HRULE] = "HRULE";
        elem_type_names[REFERENCE] = "REFERENCE";
        elem_type_names[NOTE] = "NOTE";
    }
    return elem_type_names;
}

element_type element_type_from_name(char *name)
{
    char **elem_type_names = get_element_type_names();
    
    int i;
    for (i = 0; i < NUM_LANG_TYPES; i++)
    {
        if (strcmp(elem_type_names[i], name) == 0)
            return i;
    }
    
    return NO_TYPE;
}

char *element_name_from_type(element_type type)
{
    char **elem_type_names = get_element_type_names();
    return elem_type_names[type];
}


#define IF_ATTR_NAME(x) if (strcmp(x, name) == 0)
attr_type attr_type_from_name(char *name)
{
    IF_ATTR_NAME("color") return attr_type_foreground_color;
    else IF_ATTR_NAME("foreground") return attr_type_foreground_color;
    else IF_ATTR_NAME("foreground-color") return attr_type_foreground_color;
    else IF_ATTR_NAME("background") return attr_type_background_color;
    else IF_ATTR_NAME("background-color") return attr_type_background_color;
    else IF_ATTR_NAME("font-size") return attr_type_font_size_pt;
    else IF_ATTR_NAME("font-family") return attr_type_font_family;
    else IF_ATTR_NAME("font-style") return attr_type_font_style;
    else IF_ATTR_NAME("font-weight") return attr_type_font_weight;
    return attr_type_other;
}

char *attr_name_from_type(attr_type type)
{
    switch (type)
    {
        case attr_type_foreground_color:
            return "foreground-color"; break;
        case attr_type_background_color:
            return "background-color"; break;
        case attr_type_font_size_pt:
            return "font-size"; break;
        case attr_type_font_family:
            return "font-family"; break;
        case attr_type_font_style:
            return "font-style"; break;
        case attr_type_font_weight:
            return "font-weight"; break;
        default:
            return "unknown";
    }
}


void report_error(style_parser_data *p_data, char *str, ...)
{
    if (p_data->error_callback == NULL)
        return;
    va_list argptr;
    va_start(argptr, str);
    char *errmsg;
    our_vasprintf(&errmsg, str, argptr);
    va_end(argptr);
    p_data->error_callback(errmsg);
    free(errmsg);
}


char *trim_str(char *str)
{
    while (isspace(*str))
        str++;
    if (*str == '\0')
        return str;
    char *end = str + strlen(str) - 1;
    while (end > str && isspace(*end))
        end--;
    *(end+1) = '\0';
    return str;
}


#define EQUALS(a,b) (strcmp(a, b) == 0)
style_attribute *interpret_attributes(style_parser_data *p_data,
                                      element_type lang_element_type,
                                      sem_value *raw_attributes)
{
    style_attribute *attrs = NULL;
    
    sem_value *cur = raw_attributes;
    while (cur != NULL)
    {
        attr_type atype = attr_type_from_name(cur->name);
        style_attribute *attr = new_attr(cur->name, atype);
        attr->lang_element_type = lang_element_type;
        attr->value = new_attr_value();
        
        if (atype == attr_type_foreground_color
            || atype == attr_type_background_color)
        {
            // todo: handle conversion errors somehow
            char *hexstr = trim_str(cur->value);
            attr->value->argb_color = new_argb_from_hex_str(hexstr);
        }
        else if (atype == attr_type_font_size_pt)
        {
            // todo: trim non-digits off from value (e.g. "14pt")
            // todo: handle conversion errors somehow
            attr->value->font_size_pt = atoi(cur->value);
        }
        else if (atype == attr_type_font_family)
        {
            attr->value->font_family = strdup(cur->value);
        }
        else if (atype == attr_type_font_style)
        {
            // todo: standardize input (trim; lowercase)
            attr_font_style style = attr_font_style_normal;
            if (EQUALS(cur->value, "italic"))
                style = attr_font_style_italic;
            else if (EQUALS(cur->value, "condensed"))
                style = attr_font_style_condensed;
            else
                report_error(p_data, "Value '%s' is invalid for attribute '%s'",
                             cur->value, cur->name);
            attr->value->font_style = style;
        }
        else if (atype == attr_type_font_weight)
        {
            // todo: standardize input (trim; lowercase)
            attr_font_weight weight = attr_font_weight_normal;
            if (EQUALS(cur->value, "bold"))
                weight = attr_font_weight_bold;
            else
                report_error(p_data, "Value '%s' is invalid for attribute '%s'",
                             cur->value, cur->name);
            attr->value->font_weight = weight;
        }
        else if (atype == attr_type_other)
        {
            attr->value->string = strdup(cur->value);
        }
        
        // add to linked list
        attr->next = attrs;
        attrs = attr;
        
        cur = cur->next;
    }
    
    return attrs;
}


// The element_type value that stands in as an indicator of "editor-wide"
// style definitions:
#define EDITOR_STYLE_TYPE  SEPARATOR

void interpret_and_add_style(style_parser_data *p_data,
                             char *element_type_name,
                             sem_value *raw_attributes)
{
    element_type type = element_type_from_name(element_type_name);
    if (EQUALS(element_type_name, "editor"))
        type = EDITOR_STYLE_TYPE;
    if (type == NO_TYPE) {
        report_error(p_data,
            "Style rule '%s' is not a language element type name or 'editor'",
            element_type_name);
        return;
    }
    style_attribute *attrs = interpret_attributes(p_data, type, raw_attributes);
    if (type == EDITOR_STYLE_TYPE)
        p_data->styles->editor_styles = attrs;
    else
        p_data->styles->element_styles[(p_data->styles_pos)++] = attrs;
}



# define YYSTYPE sem_value *
#ifdef __DEBUG__
# define YY_DEBUG 1
#endif

#define YY_INPUT(buf, result, max_size) YY_NAME(input_func)(buf, &result, max_size, (style_parser_data *)G->data)
void YY_NAME(input_func)(char *buf, int *result, int max_size, style_parser_data *p_data)
{
    int yyc = *(p_data->input + p_data->pos++);
    (*result) = (EOF == yyc) ? 0 : (*(buf) = yyc, 1);
}

#define SEMVAL  new_sem_value(strdup(yytext), NULL);
/* ======================================================================== */

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)     static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)    static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)      static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)     T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)                 \
  {                                                     \
    int yyc= getchar();                                 \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yyprintf((stderr, "<%c>", yyc));                  \
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN        ( G->begin= G->pos, 1)
#endif
#ifndef YY_END
#define YY_END          ( G->end= G->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args) fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE int
#endif
#ifndef YY_XTYPE
#define YY_XTYPE void *
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 1024
#endif

#ifndef YY_PART
#define yydata G->data
#define yy G->ss

struct _yythunk; // forward declaration
typedef void (*yyaction)(struct _GREG *G, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

typedef struct _GREG {
  char *buf;
  int buflen;
  int   offset;
  int   pos;
  int   limit;
  char *text;
  int   textlen;
  int   begin;
  int   end;
  yythunk *thunks;
  int   thunkslen;
  int thunkpos;
  YYSTYPE ss;
  YYSTYPE *val;
  YYSTYPE *vals;
  int valslen;
  YY_XTYPE data;
} GREG;

YY_LOCAL(int) yyrefill(GREG *G)
{
  int yyn;
  while (G->buflen - G->pos < 512)
    {
      G->buflen *= 2;
      G->buf= (char *)YY_REALLOC(G->buf, G->buflen, G->data);
    }
  YY_INPUT((G->buf + G->pos), yyn, (G->buflen - G->pos));
  if (!yyn) return 0;
  G->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *G)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  ++G->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(GREG *G, int c)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  if ((unsigned char)G->buf[G->pos] == c)
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *G, char *s)
{
  int yysav= G->pos;
  while (*s)
    {
      if (G->pos >= G->limit && !yyrefill(G)) return 0;
      if (G->buf[G->pos] != *s)
        {
          G->pos= yysav;
          return 0;
        }
      ++s;
      ++G->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *G, unsigned char *bits)
{
  int c;
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  c= (unsigned char)G->buf[G->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", G->buf+G->pos));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *G, yyaction action, int begin, int end)
{
  while (G->thunkpos >= G->thunkslen)
    {
      G->thunkslen *= 2;
      G->thunks= (yythunk *)YY_REALLOC(G->thunks, sizeof(yythunk) * G->thunkslen, G->data);
    }
  G->thunks[G->thunkpos].begin=  begin;
  G->thunks[G->thunkpos].end=    end;
  G->thunks[G->thunkpos].action= action;
  ++G->thunkpos;
}

YY_LOCAL(int) yyText(GREG *G, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (G->textlen < (yyleng - 1))
        {
          G->textlen *= 2;
          G->text= (char *)YY_REALLOC(G->text, G->textlen, G->data);
        }
      memcpy(G->text, G->buf + begin, yyleng);
    }
  G->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *G)
{
  int pos;
  for (pos= 0; pos < G->thunkpos; ++pos)
    {
      yythunk *thunk= &G->thunks[pos];
      int yyleng= thunk->end ? yyText(G, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, G->text));
      thunk->action(G, G->text, yyleng, thunk, G->data);
    }
  G->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *G)
{
  if ((G->limit -= G->pos))
    {
      memmove(G->buf, G->buf + G->pos, G->limit);
    }
  G->offset += G->pos;
  G->begin -= G->pos;
  G->end -= G->pos;
  G->pos= G->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *G, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(G);
      yyCommit(G);
    }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) { G->val += count; }
YY_LOCAL(void) yyPop(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val -= count; }
YY_LOCAL(void) yySet(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val[count]= G->ss; }

#endif /* YY_PART */

#define YYACCEPT        yyAccept(G, yythunkpos0)

YY_RULE(int) yy_Spacechar(GREG *G); /* 18 */
YY_RULE(int) yy_BeginLineComment(GREG *G); /* 17 */
YY_RULE(int) yy_AttrValueChar(GREG *G); /* 16 */
YY_RULE(int) yy_AttrNameChar(GREG *G); /* 15 */
YY_RULE(int) yy_AssignOp(GREG *G); /* 14 */
YY_RULE(int) yy_Eof(GREG *G); /* 13 */
YY_RULE(int) yy_StyleAttr(GREG *G); /* 12 */
YY_RULE(int) yy_Indent(GREG *G); /* 11 */
YY_RULE(int) yy_StyleLabelChar(GREG *G); /* 10 */
YY_RULE(int) yy_StyleAttrLine(GREG *G); /* 9 */
YY_RULE(int) yy_Newline(GREG *G); /* 8 */
YY_RULE(int) yy_Sp(GREG *G); /* 7 */
YY_RULE(int) yy_StyleLabel(GREG *G); /* 6 */
YY_RULE(int) yy_StartList(GREG *G); /* 5 */
YY_RULE(int) yy_StyleDef(GREG *G); /* 4 */
YY_RULE(int) yy_LineComment(GREG *G); /* 3 */
YY_RULE(int) yy_BlankLine(GREG *G); /* 2 */
YY_RULE(int) yy_Doc(GREG *G); /* 1 */

YY_ACTION(void) yy_2_StyleAttr(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_StyleAttr\n"));
   yy->value = strdup(yytext); ;
}
YY_ACTION(void) yy_1_StyleAttr(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StyleAttr\n"));
   yy = SEMVAL; ;
}
YY_ACTION(void) yy_1_StyleAttrLine(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
  yyprintf((stderr, "do yy_1_StyleAttrLine\n"));
   yy = a; ;
#undef a
}
YY_ACTION(void) yy_1_StyleLabel(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StyleLabel\n"));
   yy = SEMVAL; ;
}
YY_ACTION(void) yy_2_StyleDef(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
#define l G->val[-2]
#define x G->val[-3]
  yyprintf((stderr, "do yy_2_StyleDef\n"));
   interpret_and_add_style((style_parser_data *)G->data,
                                          l->name, x);
                ;
#undef a
#undef l
#undef x
}
YY_ACTION(void) yy_1_StyleDef(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
#define l G->val[-2]
#define x G->val[-3]
  yyprintf((stderr, "do yy_1_StyleDef\n"));
   x = cons(a, x); ;
#undef a
#undef l
#undef x
}
YY_ACTION(void) yy_1_StartList(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StartList\n"));
   yy = NULL; ;
}

YY_RULE(int) yy_Spacechar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Spacechar"));
  {  int yypos2= G->pos, yythunkpos2= G->thunkpos;  if (!yymatchChar(G, ' ')) goto l3;  goto l2;
  l3:;	  G->pos= yypos2; G->thunkpos= yythunkpos2;  if (!yymatchChar(G, '\t')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Spacechar", G->buf+G->pos));
  return 1;
  l1:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Spacechar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BeginLineComment(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BeginLineComment"));  if (!yymatchChar(G, '#')) goto l4;
  yyprintf((stderr, "  ok   %s @ %s\n", "BeginLineComment", G->buf+G->pos));
  return 1;
  l4:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BeginLineComment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AttrValueChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AttrValueChar"));
  {  int yypos6= G->pos, yythunkpos6= G->thunkpos;  if (!yy_Newline(G)) { goto l6; }  goto l5;
  l6:;	  G->pos= yypos6; G->thunkpos= yythunkpos6;
  }
  {  int yypos7= G->pos, yythunkpos7= G->thunkpos;  if (!yy_Eof(G)) { goto l7; }  goto l5;
  l7:;	  G->pos= yypos7; G->thunkpos= yythunkpos7;
  }
  {  int yypos8= G->pos, yythunkpos8= G->thunkpos;  if (!yy_BeginLineComment(G)) { goto l8; }  goto l5;
  l8:;	  G->pos= yypos8; G->thunkpos= yythunkpos8;
  }  if (!yymatchDot(G)) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "AttrValueChar", G->buf+G->pos));
  return 1;
  l5:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AttrValueChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AttrNameChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AttrNameChar"));  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "AttrNameChar", G->buf+G->pos));
  return 1;
  l9:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AttrNameChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AssignOp(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AssignOp"));
  {  int yypos11= G->pos, yythunkpos11= G->thunkpos;  if (!yymatchChar(G, ':')) goto l12;  goto l11;
  l12:;	  G->pos= yypos11; G->thunkpos= yythunkpos11;  if (!yymatchChar(G, '=')) goto l10;
  }
  l11:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AssignOp", G->buf+G->pos));
  return 1;
  l10:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AssignOp", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Eof(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Eof"));
  {  int yypos14= G->pos, yythunkpos14= G->thunkpos;  if (!yymatchDot(G)) goto l14;  goto l13;
  l14:;	  G->pos= yypos14; G->thunkpos= yythunkpos14;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Eof", G->buf+G->pos));
  return 1;
  l13:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Eof", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleAttr(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleAttr"));  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l15;  if (!yy_AttrNameChar(G)) { goto l15; }
  l16:;	
  {  int yypos17= G->pos, yythunkpos17= G->thunkpos;  if (!yy_AttrNameChar(G)) { goto l17; }  goto l16;
  l17:;	  G->pos= yypos17; G->thunkpos= yythunkpos17;
  }  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l15;  yyDo(G, yy_1_StyleAttr, G->begin, G->end);  if (!yy_Sp(G)) { goto l15; }  if (!yy_AssignOp(G)) { goto l15; }  if (!yy_Sp(G)) { goto l15; }  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l15;  if (!yy_AttrValueChar(G)) { goto l15; }
  l18:;	
  {  int yypos19= G->pos, yythunkpos19= G->thunkpos;  if (!yy_AttrValueChar(G)) { goto l19; }  goto l18;
  l19:;	  G->pos= yypos19; G->thunkpos= yythunkpos19;
  }  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l15;  yyDo(G, yy_2_StyleAttr, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleAttr", G->buf+G->pos));
  return 1;
  l15:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleAttr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Indent(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Indent"));
  {  int yypos21= G->pos, yythunkpos21= G->thunkpos;  if (!yymatchChar(G, '\t')) goto l22;  goto l21;
  l22:;	  G->pos= yypos21; G->thunkpos= yythunkpos21;  if (!yymatchString(G, "    ")) goto l20;
  }
  l21:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Indent", G->buf+G->pos));
  return 1;
  l20:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Indent", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleLabelChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleLabelChar"));  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l23;
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleLabelChar", G->buf+G->pos));
  return 1;
  l23:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleLabelChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleAttrLine(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "StyleAttrLine"));
  {  int yypos25= G->pos, yythunkpos25= G->thunkpos;  if (!yy_Indent(G)) { goto l25; }  goto l26;
  l25:;	  G->pos= yypos25; G->thunkpos= yythunkpos25;
  }
  l26:;	  if (!yy_StyleAttr(G)) { goto l24; }  yyDo(G, yySet, -1, 0);  if (!yy_Sp(G)) { goto l24; }
  {  int yypos27= G->pos, yythunkpos27= G->thunkpos;  if (!yy_LineComment(G)) { goto l28; }  goto l27;
  l28:;	  G->pos= yypos27; G->thunkpos= yythunkpos27;  if (!yy_Newline(G)) { goto l29; }  goto l27;
  l29:;	  G->pos= yypos27; G->thunkpos= yythunkpos27;  if (!yy_Eof(G)) { goto l24; }
  }
  l27:;	  yyDo(G, yy_1_StyleAttrLine, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleAttrLine", G->buf+G->pos));  yyDo(G, yyPop, 1, 0);
  return 1;
  l24:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleAttrLine", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Newline(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Newline"));
  {  int yypos31= G->pos, yythunkpos31= G->thunkpos;  if (!yymatchChar(G, '\n')) goto l32;  goto l31;
  l32:;	  G->pos= yypos31; G->thunkpos= yythunkpos31;  if (!yymatchChar(G, '\r')) goto l30;
  {  int yypos33= G->pos, yythunkpos33= G->thunkpos;  if (!yymatchChar(G, '\n')) goto l33;  goto l34;
  l33:;	  G->pos= yypos33; G->thunkpos= yythunkpos33;
  }
  l34:;	
  }
  l31:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Newline", G->buf+G->pos));
  return 1;
  l30:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Newline", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Sp(GREG *G)
{
  yyprintf((stderr, "%s\n", "Sp"));
  l36:;	
  {  int yypos37= G->pos, yythunkpos37= G->thunkpos;  if (!yy_Spacechar(G)) { goto l37; }  goto l36;
  l37:;	  G->pos= yypos37; G->thunkpos= yythunkpos37;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Sp", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_StyleLabel(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleLabel"));  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l38;
  {  int yypos39= G->pos, yythunkpos39= G->thunkpos;  if (!yymatchString(G, "editor")) goto l40;  goto l39;
  l40:;	  G->pos= yypos39; G->thunkpos= yythunkpos39;  if (!yy_StyleLabelChar(G)) { goto l38; }
  l41:;	
  {  int yypos42= G->pos, yythunkpos42= G->thunkpos;  if (!yy_StyleLabelChar(G)) { goto l42; }  goto l41;
  l42:;	  G->pos= yypos42; G->thunkpos= yythunkpos42;
  }
  }
  l39:;	  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l38;  yyDo(G, yy_1_StyleLabel, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleLabel", G->buf+G->pos));
  return 1;
  l38:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleLabel", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StartList(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StartList"));
  {  int yypos44= G->pos, yythunkpos44= G->thunkpos;  if (!yymatchDot(G)) goto l43;  G->pos= yypos44; G->thunkpos= yythunkpos44;
  }  yyDo(G, yy_1_StartList, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StartList", G->buf+G->pos));
  return 1;
  l43:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StartList", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleDef(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "StyleDef"));  if (!yy_StartList(G)) { goto l45; }  yyDo(G, yySet, -3, 0);  if (!yy_StyleLabel(G)) { goto l45; }  yyDo(G, yySet, -2, 0);  if (!yy_Sp(G)) { goto l45; }
  {  int yypos46= G->pos, yythunkpos46= G->thunkpos;  if (!yy_LineComment(G)) { goto l47; }  goto l46;
  l47:;	  G->pos= yypos46; G->thunkpos= yythunkpos46;  if (!yy_Newline(G)) { goto l45; }
  }
  l46:;	  if (!yy_StyleAttrLine(G)) { goto l45; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_StyleDef, G->begin, G->end);
  l48:;	
  {  int yypos49= G->pos, yythunkpos49= G->thunkpos;  if (!yy_StyleAttrLine(G)) { goto l49; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_StyleDef, G->begin, G->end);  goto l48;
  l49:;	  G->pos= yypos49; G->thunkpos= yythunkpos49;
  }  yyDo(G, yy_2_StyleDef, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleDef", G->buf+G->pos));  yyDo(G, yyPop, 3, 0);
  return 1;
  l45:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleDef", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LineComment(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LineComment"));  if (!yy_BeginLineComment(G)) { goto l50; }
  l51:;	
  {  int yypos52= G->pos, yythunkpos52= G->thunkpos;
  {  int yypos53= G->pos, yythunkpos53= G->thunkpos;  if (!yy_Newline(G)) { goto l53; }  goto l52;
  l53:;	  G->pos= yypos53; G->thunkpos= yythunkpos53;
  }
  {  int yypos54= G->pos, yythunkpos54= G->thunkpos;  if (!yy_Eof(G)) { goto l54; }  goto l52;
  l54:;	  G->pos= yypos54; G->thunkpos= yythunkpos54;
  }  if (!yymatchDot(G)) goto l52;  goto l51;
  l52:;	  G->pos= yypos52; G->thunkpos= yythunkpos52;
  }
  {  int yypos55= G->pos, yythunkpos55= G->thunkpos;  if (!yy_Newline(G)) { goto l56; }  goto l55;
  l56:;	  G->pos= yypos55; G->thunkpos= yythunkpos55;  if (!yy_Eof(G)) { goto l50; }
  }
  l55:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "LineComment", G->buf+G->pos));
  return 1;
  l50:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LineComment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BlankLine(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BlankLine"));  if (!yy_Sp(G)) { goto l57; }  if (!yy_Newline(G)) { goto l57; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BlankLine", G->buf+G->pos));
  return 1;
  l57:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BlankLine", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Doc(GREG *G)
{
  yyprintf((stderr, "%s\n", "Doc"));
  l59:;	
  {  int yypos60= G->pos, yythunkpos60= G->thunkpos;
  l61:;	
  {  int yypos62= G->pos, yythunkpos62= G->thunkpos;
  {  int yypos63= G->pos, yythunkpos63= G->thunkpos;  if (!yy_BlankLine(G)) { goto l64; }  goto l63;
  l64:;	  G->pos= yypos63; G->thunkpos= yythunkpos63;  if (!yy_LineComment(G)) { goto l62; }
  }
  l63:;	  goto l61;
  l62:;	  G->pos= yypos62; G->thunkpos= yythunkpos62;
  }  if (!yy_StyleDef(G)) { goto l60; }  goto l59;
  l60:;	  G->pos= yypos60; G->thunkpos= yythunkpos60;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Doc", G->buf+G->pos));
  return 1;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *G);

YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)
{
  int yyok;
  if (!G->buflen)
    {
      G->buflen= YY_BUFFER_START_SIZE;
      G->buf= (char *)YY_ALLOC(G->buflen, G->data);
      G->textlen= YY_BUFFER_START_SIZE;
      G->text= (char *)YY_ALLOC(G->textlen, G->data);
      G->thunkslen= YY_STACK_SIZE;
      G->thunks= (yythunk *)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);
      G->valslen= YY_STACK_SIZE;
      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);
      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;
    }
  G->pos = 0;
  G->begin= G->end= G->pos;
  G->thunkpos= 0;
  G->val= G->vals;
  yyok= yystart(G);
  if (yyok) yyDone(G);
  yyCommit(G);
  return yyok;
  (void)yyrefill(NULL);
  (void)yymatchDot(NULL);
  (void)yymatchChar(NULL, 0);
  (void)yymatchString(NULL, NULL);
  (void)yymatchClass(NULL, NULL);
  (void)yyDo(NULL, NULL, 0, 0);
  (void)yyText(NULL, 0, 0);
  (void)yyDone(NULL);
  (void)yyCommit(NULL);
  (void)yyAccept(NULL, 0);
  (void)yyPush(NULL, NULL, 0, NULL, NULL);
  (void)yyPop(NULL, NULL, 0, NULL, NULL);
  (void)yySet(NULL, NULL, 0, NULL, NULL);
}

YY_PARSE(int) YY_NAME(parse)(GREG *G)
{
  return YY_NAME(parse_from)(G, yy_Doc);
}

YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *G = (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);
  G->data = data;
  return G;
}

YY_PARSE(void) YY_NAME(parse_free)(GREG *G)
{
  YY_FREE(G->buf);
  YY_FREE(G->text);
  YY_FREE(G->thunks);
  YY_FREE(G->vals);
  YY_FREE(G);
}

#endif

/* ======================================================================== */

void _sty_parse(style_parser_data *p_data)
{
    GREG *g = YY_NAME(parse_new)(p_data);
    YY_NAME(parse)(g);
    YY_NAME(parse_free)(g);
}

style_collection *new_style_collection()
{
    style_collection *sc = (style_collection *)
                           malloc(sizeof(style_collection));
    
    sc->element_styles = (style_attribute**)
                         malloc(sizeof(style_attribute*) * NUM_LANG_TYPES);
    int i;
    for (i = 0; i < NUM_LANG_TYPES; i++)
        sc->element_styles[i] = NULL;
    
    sc->editor_styles = NULL;
    
    return sc;
}

style_parser_data *new_style_parser_data(char *input)
{
    style_parser_data *p_data = (style_parser_data*)
                                malloc(sizeof(style_parser_data));
    p_data->input = input;
    p_data->pos = 0;
    p_data->styles_pos = 0;
    p_data->styles = new_style_collection();
    return p_data;
}

style_collection *parse_styles(char *input, void(*error_callback)(char*))
{
    style_parser_data *p_data = new_style_parser_data(input);
    p_data->error_callback = error_callback;
    _sty_parse(p_data);
    return p_data->styles;
}




