/* A recursive-descent parser generated by greg 0.4.3 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct _GREG;
#define YYRULECOUNT 19

/* PEG Markdown Highlight
 * Copyright 2011 Ali Rantakari -- http://hasseg.org
 * Licensed under the GPL2+ and MIT licenses (see LICENSE for more info).
 * 
 * styleparser.leg
 * 
 */

#include "styleparser.h"
#include <stdarg.h>
#include <ctype.h>


// vasprintf is not in the C standard nor in POSIX so we provide our own
int our_vasprintf(char **strptr, const char *fmt, va_list argptr)
{
    int ret;
    va_list argptr2;
    *strptr = NULL;
    
    va_copy(argptr2, argptr);
    ret = vsnprintf(NULL, 0, fmt, argptr2);
    if (ret <= 0)
        return ret;
    
    *strptr = (char *)malloc(ret+1);
    if (*strptr == NULL)
        return -1;
    
    va_copy(argptr2, argptr);
    ret = vsnprintf(*strptr, ret+1, fmt, argptr2);
    
    return ret;
}



// Set custom symbol name prefix to avoid name collisions with the main
// PEG Markdown Highlight parser:
#define YY_NAME(N) style_yy##N


// Parsing context data
typedef struct
{
    char *input;
    int pos;
    void (*error_callback)(char*,void*);
    void *error_callback_context;
    int styles_pos;
    style_collection *styles;
} style_parser_data;

typedef struct sem_value
{
    char *name;
    char *value;
    struct sem_value *next;
} sem_value;

sem_value *new_sem_value(char *name, char *value)
{
    sem_value *v = (sem_value *)malloc(sizeof(sem_value));
    v->name = name;
    v->value = value;
    v->next = NULL;
    return v;
}

void free_sem_values(sem_value *list)
{
    sem_value *cur = list;
    while (cur != NULL)
    {
        if (cur->name != NULL) free(cur->name);
        if (cur->value != NULL) free(cur->value);
        sem_value *this = cur;
        cur = cur->next;
        free(this);
    }
}

static sem_value *cons(sem_value *elem, sem_value *list)
{
    elem->next = list;
    return elem;
}

void report_error(style_parser_data *p_data, char *str, ...)
{
    if (p_data->error_callback == NULL)
        return;
    va_list argptr;
    va_start(argptr, str);
    char *errmsg;
    our_vasprintf(&errmsg, str, argptr);
    va_end(argptr);
    p_data->error_callback(errmsg, p_data->error_callback_context);
    free(errmsg);
}



char *trim_str(char *str)
{
    while (isspace(*str))
        str++;
    if (*str == '\0')
        return str;
    char *end = str + strlen(str) - 1;
    while (end > str && isspace(*end))
        end--;
    *(end+1) = '\0';
    return str;
}

char *strcpy_lower(char *str)
{
    char *low = strdup(str);
    int i;
    int len = strlen(str);
    for (i = 0; i < len; i++)
        *(low+i) = tolower(*(low+i));
    return low;
}

char *standardize_str(char *str)
{
    return strcpy_lower(trim_str(str));
}




attr_argb_color *new_argb_color(int r, int g, int b, int a)
{
    attr_argb_color *c = (attr_argb_color *)malloc(sizeof(attr_argb_color));
    c->red = r; c->green = g; c->blue = b; c->alpha = a;
    return c;
}
attr_argb_color *new_argb_from_hex(long hex, bool has_alpha)
{
    // 0xaarrggbb
    int a = has_alpha ? ((hex >> 24) & 0xFF) : 255;
    int r = ((hex >> 16) & 0xFF);
    int g = ((hex >> 8) & 0xFF);
    int b = (hex & 0xFF);
    return new_argb_color(r,g,b,a);
}
attr_argb_color *new_argb_from_hex_str(style_parser_data *p_data, char *str)
{
    // "aarrggbb"
    int len = strlen(str);
    if (len != 6 && len != 8) {
        report_error(p_data,
                     "Value '%s' is not a valid color value: it should be a "
                     "hexadecimal number, 6 or 8 characters long.",
                     str);
        return NULL;
    }
    char *endptr = NULL;
    long num = strtol(str, &endptr, 16);
    if (*endptr != '\0') {
        report_error(p_data,
                     "Value '%s' is not a valid color value: the character "
                     "'%c' is invalid. The color value should be a hexadecimal "
                     "number, 6 or 8 characters long.",
                     str, *endptr);
        return NULL;
    }
    return new_argb_from_hex(num, (len == 8));
}

attr_value *new_attr_value()
{
    return (attr_value *)malloc(sizeof(attr_value));
}

attr_font_styles *new_font_styles()
{
    attr_font_styles *ret = (attr_font_styles *)
                            malloc(sizeof(attr_font_styles));
    ret->italic = false;
    ret->bold = false;
    ret->underlined = false;
    return ret;
}

style_attribute *new_attr(char *name, attr_type type)
{
    style_attribute *attr = (style_attribute *)malloc(sizeof(style_attribute));
    attr->name = strdup(name);
    attr->type = type;
    attr->next = NULL;
    return attr;
}

void free_style_attributes(style_attribute *list)
{
    style_attribute *cur = list;
    while (cur != NULL)
    {
        if (cur->name != NULL)
            free(cur->name);
        if (cur->value != NULL)
        {
            if (cur->type == attr_type_foreground_color
                || cur->type == attr_type_background_color
                || cur->type == attr_type_caret_color)
                free(cur->value->argb_color);
            else if (cur->type == attr_type_font_family)
                free(cur->value->font_family);
            else if (cur->type == attr_type_font_style)
                free(cur->value->font_styles);
            else if (cur->type == attr_type_other)
                free(cur->value->string);
            free(cur->value);
        }
        style_attribute *this = cur;
        cur = cur->next;
        free(this);
    }
}






char **get_element_type_names()
{
    static char **elem_type_names = NULL;
    if (elem_type_names == NULL)
    {
        elem_type_names = (char **)malloc(sizeof(char*) * pmh_NUM_LANG_TYPES);
        int i;
        for (i = 0; i < pmh_NUM_LANG_TYPES; i++)
            elem_type_names[i] = NULL;
        elem_type_names[pmh_LINK] = "LINK";
        elem_type_names[pmh_AUTO_LINK_URL] = "AUTO_LINK_URL";
        elem_type_names[pmh_AUTO_LINK_EMAIL] = "AUTO_LINK_EMAIL";
        elem_type_names[pmh_IMAGE] = "IMAGE";
        elem_type_names[pmh_CODE] = "CODE";
        elem_type_names[pmh_HTML] = "HTML";
        elem_type_names[pmh_HTML_ENTITY] = "HTML_ENTITY";
        elem_type_names[pmh_EMPH] = "EMPH";
        elem_type_names[pmh_STRONG] = "STRONG";
        elem_type_names[pmh_LIST_BULLET] = "LIST_BULLET";
        elem_type_names[pmh_LIST_ENUMERATOR] = "LIST_ENUMERATOR";
        elem_type_names[pmh_COMMENT] = "COMMENT";
        elem_type_names[pmh_H1] = "H1";
        elem_type_names[pmh_H2] = "H2";
        elem_type_names[pmh_H3] = "H3";
        elem_type_names[pmh_H4] = "H4";
        elem_type_names[pmh_H5] = "H5";
        elem_type_names[pmh_H6] = "H6";
        elem_type_names[pmh_BLOCKQUOTE] = "BLOCKQUOTE";
        elem_type_names[pmh_VERBATIM] = "VERBATIM";
        elem_type_names[pmh_HTMLBLOCK] = "HTMLBLOCK";
        elem_type_names[pmh_HRULE] = "HRULE";
        elem_type_names[pmh_REFERENCE] = "REFERENCE";
        elem_type_names[pmh_NOTE] = "NOTE";
    }
    return elem_type_names;
}

pmh_element_type element_type_from_name(char *name)
{
    char **elem_type_names = get_element_type_names();
    
    int i;
    for (i = 0; i < pmh_NUM_LANG_TYPES; i++)
    {
        char *i_name = elem_type_names[i];
        if (i_name == NULL)
            continue;
        if (strcmp(i_name, name) == 0)
            return i;
    }
    
    return pmh_NO_TYPE;
}

char *element_name_from_type(pmh_element_type type)
{
    char **elem_type_names = get_element_type_names();
    char* ret = elem_type_names[type];
    if (ret == NULL)
        return "unknown type";
    return ret;
}


#define IF_ATTR_NAME(x) if (strcmp(x, name) == 0)
attr_type attr_type_from_name(char *name)
{
    IF_ATTR_NAME("color") return attr_type_foreground_color;
    else IF_ATTR_NAME("foreground") return attr_type_foreground_color;
    else IF_ATTR_NAME("foreground-color") return attr_type_foreground_color;
    else IF_ATTR_NAME("background") return attr_type_background_color;
    else IF_ATTR_NAME("background-color") return attr_type_background_color;
    else IF_ATTR_NAME("caret") return attr_type_caret_color;
    else IF_ATTR_NAME("caret-color") return attr_type_caret_color;
    else IF_ATTR_NAME("font-size") return attr_type_font_size_pt;
    else IF_ATTR_NAME("font-family") return attr_type_font_family;
    else IF_ATTR_NAME("font-style") return attr_type_font_style;
    return attr_type_other;
}

char *attr_name_from_type(attr_type type)
{
    switch (type)
    {
        case attr_type_foreground_color:
            return "foreground-color"; break;
        case attr_type_background_color:
            return "background-color"; break;
        case attr_type_caret_color:
            return "caret-color"; break;
        case attr_type_font_size_pt:
            return "font-size"; break;
        case attr_type_font_family:
            return "font-family"; break;
        case attr_type_font_style:
            return "font-style"; break;
        default:
            return "unknown";
    }
}


typedef struct multi_value
{
    char *value;
    struct multi_value *next;
} multi_value;

multi_value *split_multi_value(char *input)
{
    multi_value *head = NULL;
    
    char *c = input;
    while (*c != '\0')
    {
        size_t i;
        for (i = 0; (*(c+i) != '\0' && *(c+i) != ','); i++);
        multi_value *mv = (multi_value *)malloc(sizeof(multi_value));
        mv->value = (char *)malloc(sizeof(char)*i + 1);
        *mv->value = '\0';
        strncat(mv->value, c, i);
        mv->next = head;
        head = mv;
        if (*(c+i) == ',')
            i++;
        c += i;
    }
    
    return head;
}

void free_multi_value(multi_value *val)
{
    multi_value *cur = val;
    while (cur != NULL)
    {
        multi_value *this = cur;
        free(this->value);
        free(this);
        cur = cur->next;
    }
}




#define EQUALS(a,b) (strcmp(a, b) == 0)
style_attribute *interpret_attributes(style_parser_data *p_data,
                                      pmh_element_type lang_element_type,
                                      sem_value *raw_attributes)
{
    style_attribute *attrs = NULL;
    
    sem_value *cur = raw_attributes;
    while (cur != NULL)
    {
        attr_type atype = attr_type_from_name(cur->name);
        style_attribute *attr = new_attr(cur->name, atype);
        attr->lang_element_type = lang_element_type;
        attr->value = new_attr_value();
        
        if (atype == attr_type_foreground_color
            || atype == attr_type_background_color
            || atype == attr_type_caret_color)
        {
            char *hexstr = trim_str(cur->value);
            // new_argb_from_hex_str() reports conversion errors
            attr->value->argb_color = new_argb_from_hex_str(p_data, hexstr);
            if (attr->value->argb_color == NULL) {
                free_style_attributes(attr);
                attr = NULL;
            }
        }
        else if (atype == attr_type_font_size_pt)
        {
            char *endptr = NULL;
            attr->value->font_size_pt = (int)strtol(cur->value, &endptr, 10);
            if (endptr == cur->value) {
                report_error(p_data, "Value '%s' is invalid for attribute '%s'",
                             cur->value, cur->name);
                free_style_attributes(attr);
                attr = NULL;
            }
        }
        else if (atype == attr_type_font_family)
        {
            attr->value->font_family = strdup(cur->value);
        }
        else if (atype == attr_type_font_style)
        {
            attr->value->font_styles = new_font_styles();
            multi_value *values = split_multi_value(cur->value);
            multi_value *value_cur = values;
            while (value_cur != NULL)
            {
                char *standardized_value = standardize_str(value_cur->value);
                
                if (EQUALS(standardized_value, "italic"))
                    attr->value->font_styles->italic = true;
                else if (EQUALS(standardized_value, "bold"))
                    attr->value->font_styles->bold = true;
                else if (EQUALS(standardized_value, "underlined"))
                    attr->value->font_styles->underlined = true;
                else {
                    report_error(p_data, "Value '%s' is invalid for attribute '%s'",
                                 standardized_value, cur->name);
                }
                
                free(standardized_value);
                value_cur = value_cur->next;
            }
            free_multi_value(values);
        }
        else if (atype == attr_type_other)
        {
            attr->value->string = strdup(cur->value);
        }
        
        if (attr != NULL) {
            // add to linked list
            attr->next = attrs;
            attrs = attr;
        }
        
        cur = cur->next;
    }
    
    return attrs;
}


void interpret_and_add_style(style_parser_data *p_data,
                             char *element_type_name,
                             sem_value *raw_attributes)
{
    bool isEditorType = false;
    bool isCurrentLineType = false;
    bool isSelectionType = false;
    pmh_element_type type = element_type_from_name(element_type_name);
    if (type == pmh_NO_TYPE)
    {
        if (EQUALS(element_type_name, "editor"))
            isEditorType = true, type = pmh_NO_TYPE;
        else if (EQUALS(element_type_name, "editor-current-line"))
            isCurrentLineType = true, type = pmh_NO_TYPE;
        else if (EQUALS(element_type_name, "editor-selection"))
            isSelectionType = true, type = pmh_NO_TYPE;
        else {
            report_error(p_data,
                "Style rule '%s' is not a language pmh_element type name or "
                "one of the following: 'editor', 'editor-current-line', "
                "'editor-selection'",
                element_type_name);
            return;
        }
    }
    style_attribute *attrs = interpret_attributes(p_data, type, raw_attributes);
    if (isEditorType)
        p_data->styles->editor_styles = attrs;
    else if (isCurrentLineType)
        p_data->styles->editor_current_line_styles = attrs;
    else if (isSelectionType)
        p_data->styles->editor_selection_styles = attrs;
    else
        p_data->styles->element_styles[(p_data->styles_pos)++] = attrs;
}



# define YYSTYPE sem_value *
#ifdef __DEBUG__
# define YY_DEBUG 1
#endif

#define YY_INPUT(buf, result, max_size) YY_NAME(input_func)(buf, &result, max_size, (style_parser_data *)G->data)
void YY_NAME(input_func)(char *buf, int *result, int max_size, style_parser_data *p_data)
{
    int yyc = *(p_data->input + p_data->pos++);
    (*result) = (EOF == yyc) ? 0 : (*(buf) = yyc, 1);
}

#define SEMVAL  new_sem_value(strdup(yytext), NULL);
/* ======================================================================== */

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)     static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)    static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)      static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)     T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)                 \
  {                                                     \
    int yyc= getchar();                                 \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yyprintf((stderr, "<%c>", yyc));                  \
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN        ( G->begin= G->pos, 1)
#endif
#ifndef YY_END
#define YY_END          ( G->end= G->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args) fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE int
#endif
#ifndef YY_XTYPE
#define YY_XTYPE void *
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 1024
#endif

#ifndef YY_PART
#define yydata G->data
#define yy G->ss

struct _yythunk; // forward declaration
typedef void (*yyaction)(struct _GREG *G, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

typedef struct _GREG {
  char *buf;
  int buflen;
  int   offset;
  int   pos;
  int   limit;
  char *text;
  int   textlen;
  int   begin;
  int   end;
  yythunk *thunks;
  int   thunkslen;
  int thunkpos;
  YYSTYPE ss;
  YYSTYPE *val;
  YYSTYPE *vals;
  int valslen;
  YY_XTYPE data;
} GREG;

YY_LOCAL(int) yyrefill(GREG *G)
{
  int yyn;
  while (G->buflen - G->pos < 512)
    {
      G->buflen *= 2;
      G->buf= (char *)YY_REALLOC(G->buf, G->buflen, G->data);
    }
  YY_INPUT((G->buf + G->pos), yyn, (G->buflen - G->pos));
  if (!yyn) return 0;
  G->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *G)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  ++G->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(GREG *G, int c)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  if ((unsigned char)G->buf[G->pos] == c)
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *G, char *s)
{
  int yysav= G->pos;
  while (*s)
    {
      if (G->pos >= G->limit && !yyrefill(G)) return 0;
      if (G->buf[G->pos] != *s)
        {
          G->pos= yysav;
          return 0;
        }
      ++s;
      ++G->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *G, unsigned char *bits)
{
  int c;
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  c= (unsigned char)G->buf[G->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", G->buf+G->pos));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *G, yyaction action, int begin, int end)
{
  while (G->thunkpos >= G->thunkslen)
    {
      G->thunkslen *= 2;
      G->thunks= (yythunk *)YY_REALLOC(G->thunks, sizeof(yythunk) * G->thunkslen, G->data);
    }
  G->thunks[G->thunkpos].begin=  begin;
  G->thunks[G->thunkpos].end=    end;
  G->thunks[G->thunkpos].action= action;
  ++G->thunkpos;
}

YY_LOCAL(int) yyText(GREG *G, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (G->textlen < (yyleng - 1))
        {
          G->textlen *= 2;
          G->text= (char *)YY_REALLOC(G->text, G->textlen, G->data);
        }
      memcpy(G->text, G->buf + begin, yyleng);
    }
  G->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *G)
{
  int pos;
  for (pos= 0; pos < G->thunkpos; ++pos)
    {
      yythunk *thunk= &G->thunks[pos];
      int yyleng= thunk->end ? yyText(G, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, G->text));
      thunk->action(G, G->text, yyleng, thunk, G->data);
    }
  G->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *G)
{
  if ((G->limit -= G->pos))
    {
      memmove(G->buf, G->buf + G->pos, G->limit);
    }
  G->offset += G->pos;
  G->begin -= G->pos;
  G->end -= G->pos;
  G->pos= G->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *G, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(G);
      yyCommit(G);
    }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) { G->val += count; }
YY_LOCAL(void) yyPop(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val -= count; }
YY_LOCAL(void) yySet(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val[count]= G->ss; }

#endif /* YY_PART */

#define YYACCEPT        yyAccept(G, yythunkpos0)

YY_RULE(int) yy_AnythingTillEol(GREG *G); /* 19 */
YY_RULE(int) yy_Spacechar(GREG *G); /* 18 */
YY_RULE(int) yy_BeginLineComment(GREG *G); /* 17 */
YY_RULE(int) yy_AttrValueChar(GREG *G); /* 16 */
YY_RULE(int) yy_AttrNameChar(GREG *G); /* 15 */
YY_RULE(int) yy_Eof(GREG *G); /* 14 */
YY_RULE(int) yy_StyleAttr(GREG *G); /* 13 */
YY_RULE(int) yy_AssignOp(GREG *G); /* 12 */
YY_RULE(int) yy_StyleLabelChar(GREG *G); /* 11 */
YY_RULE(int) yy_IndentMaybe(GREG *G); /* 10 */
YY_RULE(int) yy_StyleAttrLine(GREG *G); /* 9 */
YY_RULE(int) yy_Newline(GREG *G); /* 8 */
YY_RULE(int) yy_Sp(GREG *G); /* 7 */
YY_RULE(int) yy_StyleLabel(GREG *G); /* 6 */
YY_RULE(int) yy_StartList(GREG *G); /* 5 */
YY_RULE(int) yy_StyleDef(GREG *G); /* 4 */
YY_RULE(int) yy_LineComment(GREG *G); /* 3 */
YY_RULE(int) yy_BlankLine(GREG *G); /* 2 */
YY_RULE(int) yy_Doc(GREG *G); /* 1 */

YY_ACTION(void) yy_2_StyleAttr(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_2_StyleAttr\n"));
   yy->value = strdup(yytext); ;
}
YY_ACTION(void) yy_1_StyleAttr(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StyleAttr\n"));
   yy = SEMVAL; ;
}
YY_ACTION(void) yy_1_StyleAttrLine(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
  yyprintf((stderr, "do yy_1_StyleAttrLine\n"));
   yy = a; ;
#undef a
}
YY_ACTION(void) yy_1_StyleLabel(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StyleLabel\n"));
   yy = SEMVAL; ;
}
YY_ACTION(void) yy_2_StyleDef(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
#define l G->val[-2]
#define x G->val[-3]
  yyprintf((stderr, "do yy_2_StyleDef\n"));
   interpret_and_add_style((style_parser_data *)G->data,
                                          l->name, x);
                  free_sem_values(x);
                  free_sem_values(l);
                ;
#undef a
#undef l
#undef x
}
YY_ACTION(void) yy_1_StyleDef(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define a G->val[-1]
#define l G->val[-2]
#define x G->val[-3]
  yyprintf((stderr, "do yy_1_StyleDef\n"));
   x = cons(a, x); ;
#undef a
#undef l
#undef x
}
YY_ACTION(void) yy_1_StartList(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_StartList\n"));
   yy = NULL; ;
}

YY_RULE(int) yy_AnythingTillEol(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AnythingTillEol"));
  l2:;	
  {  int yypos3= G->pos, yythunkpos3= G->thunkpos;
  {  int yypos4= G->pos, yythunkpos4= G->thunkpos;  if (!yy_Newline(G)) { goto l4; }  goto l3;
  l4:;	  G->pos= yypos4; G->thunkpos= yythunkpos4;
  }
  {  int yypos5= G->pos, yythunkpos5= G->thunkpos;  if (!yy_Eof(G)) { goto l5; }  goto l3;
  l5:;	  G->pos= yypos5; G->thunkpos= yythunkpos5;
  }  if (!yymatchDot(G)) goto l3;  goto l2;
  l3:;	  G->pos= yypos3; G->thunkpos= yythunkpos3;
  }
  {  int yypos6= G->pos, yythunkpos6= G->thunkpos;  if (!yy_Newline(G)) { goto l7; }  goto l6;
  l7:;	  G->pos= yypos6; G->thunkpos= yythunkpos6;  if (!yy_Eof(G)) { goto l1; }
  }
  l6:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AnythingTillEol", G->buf+G->pos));
  return 1;
  l1:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AnythingTillEol", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Spacechar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Spacechar"));
  {  int yypos9= G->pos, yythunkpos9= G->thunkpos;  if (!yymatchChar(G, ' ')) goto l10;  goto l9;
  l10:;	  G->pos= yypos9; G->thunkpos= yythunkpos9;  if (!yymatchChar(G, '\t')) goto l8;
  }
  l9:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Spacechar", G->buf+G->pos));
  return 1;
  l8:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Spacechar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BeginLineComment(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BeginLineComment"));  if (!yymatchChar(G, '#')) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "BeginLineComment", G->buf+G->pos));
  return 1;
  l11:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BeginLineComment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AttrValueChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AttrValueChar"));
  {  int yypos13= G->pos, yythunkpos13= G->thunkpos;  if (!yy_Newline(G)) { goto l13; }  goto l12;
  l13:;	  G->pos= yypos13; G->thunkpos= yythunkpos13;
  }
  {  int yypos14= G->pos, yythunkpos14= G->thunkpos;  if (!yy_Eof(G)) { goto l14; }  goto l12;
  l14:;	  G->pos= yypos14; G->thunkpos= yythunkpos14;
  }
  {  int yypos15= G->pos, yythunkpos15= G->thunkpos;  if (!yy_BeginLineComment(G)) { goto l15; }  goto l12;
  l15:;	  G->pos= yypos15; G->thunkpos= yythunkpos15;
  }  if (!yymatchDot(G)) goto l12;
  yyprintf((stderr, "  ok   %s @ %s\n", "AttrValueChar", G->buf+G->pos));
  return 1;
  l12:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AttrValueChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AttrNameChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AttrNameChar"));  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "AttrNameChar", G->buf+G->pos));
  return 1;
  l16:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AttrNameChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Eof(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Eof"));
  {  int yypos18= G->pos, yythunkpos18= G->thunkpos;  if (!yymatchDot(G)) goto l18;  goto l17;
  l18:;	  G->pos= yypos18; G->thunkpos= yythunkpos18;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Eof", G->buf+G->pos));
  return 1;
  l17:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Eof", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleAttr(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleAttr"));  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l19;  if (!yy_AttrNameChar(G)) { goto l19; }
  l20:;	
  {  int yypos21= G->pos, yythunkpos21= G->thunkpos;  if (!yy_AttrNameChar(G)) { goto l21; }  goto l20;
  l21:;	  G->pos= yypos21; G->thunkpos= yythunkpos21;
  }  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l19;  yyDo(G, yy_1_StyleAttr, G->begin, G->end);  if (!yy_Sp(G)) { goto l19; }  if (!yy_AssignOp(G)) { goto l19; }  if (!yy_Sp(G)) { goto l19; }  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l19;  if (!yy_AttrValueChar(G)) { goto l19; }
  l22:;	
  {  int yypos23= G->pos, yythunkpos23= G->thunkpos;  if (!yy_AttrValueChar(G)) { goto l23; }  goto l22;
  l23:;	  G->pos= yypos23; G->thunkpos= yythunkpos23;
  }  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l19;  yyDo(G, yy_2_StyleAttr, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleAttr", G->buf+G->pos));
  return 1;
  l19:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleAttr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AssignOp(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AssignOp"));
  {  int yypos25= G->pos, yythunkpos25= G->thunkpos;  if (!yymatchChar(G, ':')) goto l26;  goto l25;
  l26:;	  G->pos= yypos25; G->thunkpos= yythunkpos25;  if (!yymatchChar(G, '=')) goto l24;
  }
  l25:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AssignOp", G->buf+G->pos));
  return 1;
  l24:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AssignOp", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleLabelChar(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleLabelChar"));  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l27;
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleLabelChar", G->buf+G->pos));
  return 1;
  l27:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleLabelChar", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_IndentMaybe(GREG *G)
{
  yyprintf((stderr, "%s\n", "IndentMaybe"));
  l29:;	
  {  int yypos30= G->pos, yythunkpos30= G->thunkpos;
  {  int yypos31= G->pos, yythunkpos31= G->thunkpos;  if (!yymatchChar(G, '\t')) goto l32;  goto l31;
  l32:;	  G->pos= yypos31; G->thunkpos= yythunkpos31;  if (!yymatchChar(G, ' ')) goto l30;
  }
  l31:;	  goto l29;
  l30:;	  G->pos= yypos30; G->thunkpos= yythunkpos30;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "IndentMaybe", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_StyleAttrLine(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "StyleAttrLine"));  if (!yy_IndentMaybe(G)) { goto l33; }  if (!yy_StyleAttr(G)) { goto l33; }  yyDo(G, yySet, -1, 0);  if (!yy_Sp(G)) { goto l33; }
  {  int yypos34= G->pos, yythunkpos34= G->thunkpos;  if (!yy_LineComment(G)) { goto l35; }  goto l34;
  l35:;	  G->pos= yypos34; G->thunkpos= yythunkpos34;  if (!yy_Newline(G)) { goto l36; }  goto l34;
  l36:;	  G->pos= yypos34; G->thunkpos= yythunkpos34;  if (!yy_Eof(G)) { goto l33; }
  }
  l34:;	  yyDo(G, yy_1_StyleAttrLine, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleAttrLine", G->buf+G->pos));  yyDo(G, yyPop, 1, 0);
  return 1;
  l33:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleAttrLine", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Newline(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Newline"));
  {  int yypos38= G->pos, yythunkpos38= G->thunkpos;  if (!yymatchChar(G, '\n')) goto l39;  goto l38;
  l39:;	  G->pos= yypos38; G->thunkpos= yythunkpos38;  if (!yymatchChar(G, '\r')) goto l37;
  {  int yypos40= G->pos, yythunkpos40= G->thunkpos;  if (!yymatchChar(G, '\n')) goto l40;  goto l41;
  l40:;	  G->pos= yypos40; G->thunkpos= yythunkpos40;
  }
  l41:;	
  }
  l38:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Newline", G->buf+G->pos));
  return 1;
  l37:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Newline", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Sp(GREG *G)
{
  yyprintf((stderr, "%s\n", "Sp"));
  l43:;	
  {  int yypos44= G->pos, yythunkpos44= G->thunkpos;  if (!yy_Spacechar(G)) { goto l44; }  goto l43;
  l44:;	  G->pos= yypos44; G->thunkpos= yythunkpos44;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Sp", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_StyleLabel(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StyleLabel"));  if (!yy_IndentMaybe(G)) { goto l45; }  yyText(G, G->begin, G->end);  if (!(YY_BEGIN)) goto l45;  if (!yy_StyleLabelChar(G)) { goto l45; }
  l46:;	
  {  int yypos47= G->pos, yythunkpos47= G->thunkpos;  if (!yy_StyleLabelChar(G)) { goto l47; }  goto l46;
  l47:;	  G->pos= yypos47; G->thunkpos= yythunkpos47;
  }  yyText(G, G->begin, G->end);  if (!(YY_END)) goto l45;  yyDo(G, yy_1_StyleLabel, G->begin, G->end);  if (!yy_Sp(G)) { goto l45; }
  {  int yypos48= G->pos, yythunkpos48= G->thunkpos;  if (!yy_AssignOp(G)) { goto l48; }  goto l49;
  l48:;	  G->pos= yypos48; G->thunkpos= yythunkpos48;
  }
  l49:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleLabel", G->buf+G->pos));
  return 1;
  l45:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleLabel", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StartList(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "StartList"));
  {  int yypos51= G->pos, yythunkpos51= G->thunkpos;  if (!yymatchDot(G)) goto l50;  G->pos= yypos51; G->thunkpos= yythunkpos51;
  }  yyDo(G, yy_1_StartList, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StartList", G->buf+G->pos));
  return 1;
  l50:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StartList", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_StyleDef(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "StyleDef"));  if (!yy_StartList(G)) { goto l52; }  yyDo(G, yySet, -3, 0);  if (!yy_StyleLabel(G)) { goto l52; }  yyDo(G, yySet, -2, 0);  if (!yy_Sp(G)) { goto l52; }
  {  int yypos53= G->pos, yythunkpos53= G->thunkpos;  if (!yy_LineComment(G)) { goto l54; }  goto l53;
  l54:;	  G->pos= yypos53; G->thunkpos= yythunkpos53;  if (!yy_Newline(G)) { goto l52; }
  }
  l53:;	
  {  int yypos57= G->pos, yythunkpos57= G->thunkpos;  if (!yy_StyleAttrLine(G)) { goto l58; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_StyleDef, G->begin, G->end);  goto l57;
  l58:;	  G->pos= yypos57; G->thunkpos= yythunkpos57;  if (!yy_IndentMaybe(G)) { goto l52; }  if (!yy_LineComment(G)) { goto l52; }
  }
  l57:;	
  l55:;	
  {  int yypos56= G->pos, yythunkpos56= G->thunkpos;
  {  int yypos59= G->pos, yythunkpos59= G->thunkpos;  if (!yy_StyleAttrLine(G)) { goto l60; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_StyleDef, G->begin, G->end);  goto l59;
  l60:;	  G->pos= yypos59; G->thunkpos= yythunkpos59;  if (!yy_IndentMaybe(G)) { goto l56; }  if (!yy_LineComment(G)) { goto l56; }
  }
  l59:;	  goto l55;
  l56:;	  G->pos= yypos56; G->thunkpos= yythunkpos56;
  }  yyDo(G, yy_2_StyleDef, G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "StyleDef", G->buf+G->pos));  yyDo(G, yyPop, 3, 0);
  return 1;
  l52:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "StyleDef", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LineComment(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LineComment"));  if (!yy_BeginLineComment(G)) { goto l61; }  if (!yy_AnythingTillEol(G)) { goto l61; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LineComment", G->buf+G->pos));
  return 1;
  l61:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LineComment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BlankLine(GREG *G)
{  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BlankLine"));  if (!yy_Sp(G)) { goto l62; }  if (!yy_Newline(G)) { goto l62; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BlankLine", G->buf+G->pos));
  return 1;
  l62:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BlankLine", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Doc(GREG *G)
{
  yyprintf((stderr, "%s\n", "Doc"));
  l64:;	
  {  int yypos65= G->pos, yythunkpos65= G->thunkpos;
  l66:;	
  {  int yypos67= G->pos, yythunkpos67= G->thunkpos;
  {  int yypos68= G->pos, yythunkpos68= G->thunkpos;  if (!yy_BlankLine(G)) { goto l69; }  goto l68;
  l69:;	  G->pos= yypos68; G->thunkpos= yythunkpos68;  if (!yy_LineComment(G)) { goto l67; }
  }
  l68:;	  goto l66;
  l67:;	  G->pos= yypos67; G->thunkpos= yythunkpos67;
  }  if (!yy_StyleDef(G)) { goto l65; }  goto l64;
  l65:;	  G->pos= yypos65; G->thunkpos= yythunkpos65;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Doc", G->buf+G->pos));
  return 1;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *G);

YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)
{
  int yyok;
  if (!G->buflen)
    {
      G->buflen= YY_BUFFER_START_SIZE;
      G->buf= (char *)YY_ALLOC(G->buflen, G->data);
      G->textlen= YY_BUFFER_START_SIZE;
      G->text= (char *)YY_ALLOC(G->textlen, G->data);
      G->thunkslen= YY_STACK_SIZE;
      G->thunks= (yythunk *)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);
      G->valslen= YY_STACK_SIZE;
      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);
      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;
    }
  G->pos = 0;
  G->begin= G->end= G->pos;
  G->thunkpos= 0;
  G->val= G->vals;
  yyok= yystart(G);
  if (yyok) yyDone(G);
  yyCommit(G);
  return yyok;
  (void)yyrefill(NULL);
  (void)yymatchDot(NULL);
  (void)yymatchChar(NULL, 0);
  (void)yymatchString(NULL, NULL);
  (void)yymatchClass(NULL, NULL);
  (void)yyDo(NULL, NULL, 0, 0);
  (void)yyText(NULL, 0, 0);
  (void)yyDone(NULL);
  (void)yyCommit(NULL);
  (void)yyAccept(NULL, 0);
  (void)yyPush(NULL, NULL, 0, NULL, NULL);
  (void)yyPop(NULL, NULL, 0, NULL, NULL);
  (void)yySet(NULL, NULL, 0, NULL, NULL);
}

YY_PARSE(int) YY_NAME(parse)(GREG *G)
{
  return YY_NAME(parse_from)(G, yy_Doc);
}

YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *G = (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);
  G->data = data;
  return G;
}

YY_PARSE(void) YY_NAME(parse_free)(GREG *G)
{
  YY_FREE(G->buf);
  YY_FREE(G->text);
  YY_FREE(G->thunks);
  YY_FREE(G->vals);
  YY_FREE(G);
}

#endif

/* ======================================================================== */

void _sty_parse(style_parser_data *p_data)
{
    GREG *g = YY_NAME(parse_new)(p_data);
    YY_NAME(parse)(g);
    YY_NAME(parse_free)(g);
}

style_collection *new_style_collection()
{
    style_collection *sc = (style_collection *)
                           malloc(sizeof(style_collection));
    
    sc->element_styles = (style_attribute**)
                         malloc(sizeof(style_attribute*) * pmh_NUM_LANG_TYPES);
    int i;
    for (i = 0; i < pmh_NUM_LANG_TYPES; i++)
        sc->element_styles[i] = NULL;
    
    sc->editor_styles = NULL;
    sc->editor_current_line_styles = NULL;
    sc->editor_selection_styles = NULL;
    
    return sc;
}

void free_style_collection(style_collection *coll)
{
    free_style_attributes(coll->editor_styles);
    free_style_attributes(coll->editor_current_line_styles);
    free_style_attributes(coll->editor_selection_styles);
    int i;
    for (i = 0; i < pmh_NUM_LANG_TYPES; i++)
        free_style_attributes(coll->element_styles[i]);
    free(coll->element_styles);
    free(coll);
}

style_parser_data *new_style_parser_data(char *input)
{
    style_parser_data *p_data = (style_parser_data*)
                                malloc(sizeof(style_parser_data));
    p_data->input = input;
    p_data->pos = 0;
    p_data->styles_pos = 0;
    p_data->styles = new_style_collection();
    return p_data;
}

style_collection *parse_styles(char *input, void(*error_callback)(char*,void*),
                               void *error_callback_context)
{
    style_parser_data *p_data = new_style_parser_data(input);
    p_data->error_callback = error_callback;
    p_data->error_callback_context = error_callback_context;
    
    _sty_parse(p_data);
    
    style_collection *ret = p_data->styles;
    free(p_data);
    return ret;
}



